SELECT DATEDIFF(SECOND, PAC_DATA_INICIAL, PAC_DATA_FINAL) AS DIFERENCA_SEGUNDOS,
CONVERT(DATE, PAC_DATA_INICIAL) AS DATA,
FUN_ID
FROM PAC_PONTOS_ACESSO;

INSERT INTO PAC_PONTOS_ACESSO(PAC_DATA_INICIAL, PAC_DATA_FINAL, FUN_ID) 
VALUES ('2017-02-01 13:02:00', '2017-02-01 17:07:00', 1);

SELECT * FROM PAC_PONTOS_ACESSO;

CREATE FUNCTION FN_CALCULA_HORA(@P_QTDE_SEGUNDOS INT)
RETURNS VARCHAR(8) AS 
BEGIN
	RETURN FORMAT(@P_QTDE_SEGUNDOS/3600, '00') + ':' +
			FORMAT(@P_QTDE_SEGUNDOS%3600)/60, '00') + ':' +
			FORMAT(((@P_QTDE_SEGUNDOS%3600)%¨60), '00')
END;